version: '3.8'
services:
  db:
    image: timescale/timescaledb:2.15.0-pg14
    container_name: choru-timescaledb
    environment:
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
      POSTGRES_DB: choru_stock
    volumes:
      - timescale-data:/var/lib/postgresql/data
      - ./sql/init-timescaledb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: choru-stock-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/choru_stock
      SPRING_DATASOURCE_USERNAME: stock_user
      SPRING_DATASOURCE_PASSWORD: stock_pass
      SERVER_PORT: 8081
      APP_PRICE_SYNC_INTERVAL_MS: 1000
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true

volumes:
  timescale-data: