server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/choru_stock}
    username: ${SPRING_DATASOURCE_USERNAME:stock_user}
    password: ${SPRING_DATASOURCE_PASSWORD:stock_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

