spring:
  application:
    name: choru-stock
  task:
    scheduling:
      pool:
        size: 2
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/choru_stock}
    username: ${SPRING_DATASOURCE_USERNAME:stock_user}
    password: ${SPRING_DATASOURCE_PASSWORD:stock_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
exchange:
  base-url: http://localhost:8081

server:
  port: ${SERVER_PORT:8080}

app:
  price-sync:
    interval-ms: ${APP_PRICE_SYNC_INTERVAL_MS:500}
