server:
  port: ${SERVER_PORT:8082}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka:
  topic: ticks

exchange:
  base-url: ${EXCHANGE_BASE_URL:http://localhost:8084}

poll:
  interval: 1000

